server:
  host: localhost
  port: "8888"

services:
  pool:
    - localhost:9001
    - localhost:9002
    - localhost:9003
    - localhost:9004

health:
  timeout_ms: 500
  ticker_ms: 5000

limiter:
  capacity: 1
  ticker_ms: 5000